// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwlwkzpfaoydlufsrdau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3bHdrenBmYW95ZGx1ZnNyZGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTE2NzksImV4cCI6MjA2NDY4NzY3OX0.pGWpxD_hnJ0KCYrAzpJArQuL0p0rRy48lcAPv6H3Dv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);